{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-teal.code
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/teal.code_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/teal.code/teal.code_{{ version }}.tar.gz
  sha256: 79df6e33694b89923b938069c8ae3f1f5fce2760b019b276e5e8902bb5ed4b06

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-cli >=3.4.0
    - r-evaluate >=1.0.0
    - r-lifecycle >=0.2.0
    - r-rlang >=1.1.0
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-cli >=3.4.0
    - r-evaluate >=1.0.0
    - r-lifecycle >=0.2.0
    - r-rlang >=1.1.0

test:
  commands:
    - $R -e "library('teal.code')"           # [not win]
    - "\"%R%\" -e \"library('teal.code')\""  # [win]

about:
  home: https://insightsengineering.github.io/teal.code/, https://github.com/insightsengineering/teal.code
  license: Apache-2.0
  summary: Introduction of 'qenv' S4 class, that facilitates code execution and reproducibility in 'teal' applications.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
